#! /bin/bash
#

PRG=ma_test.exe
if [ -n "$1" ]; then
       PRG=$1
       shift
fi

if [ ! -x ~ma/bin/sy2l.tcl ]; then
	exec ./$PRG
fi

LPIPE=Y2LOGFILE
test -p "$LPIPE" || {
        test -e "$LPIPE" && { echo "No pipe '$LPIPE' exists"; exit 1; }
        mkfifo $LPIPE
}
if ! fuser $LPIPE >/dev/null; then
        ~ma/bin/sy1l.tcl $LPIPE &
fi

echo > $LPIPE
make -C ../../src && make $PRG || exit 1

export Y2SLOG_FILE=-
# export Y2SLOG_DEBUG=
# export Y2DEBUG=1
# exec gdb ./$PRG
#./$PRG "$@" 2> log
./$PRG "$@" 2> $LPIPE
