#! /bin/bash
#
export LD_LIBRARY_PATH=/usr/local/lib64

PRG=ma_test.bin
if [ -n "$1" ]; then
       PRG=$1
       shift
fi

if [ ! -x ~ma/bin/sy2l.tcl ]; then
	exec ./$PRG
fi

LPIPE=Y2LOGFILE
test -p "$LPIPE" || {
        test -e "$LPIPE" && { echo "No pipe '$LPIPE' exists"; exit 1; }
        mkfifo $LPIPE
}
if ! fuser $LPIPE >/dev/null; then
	#echo
        ~ma/bin/sy2l.tcl $LPIPE &
fi

if ps axl | grep -q '[/]usr/sbin/iceczc'; then
	MAKE=make
else
	MAKE="make -j 15"
fi


$MAKE -C ../../src || exit 1
#if [ $PRG == wfm_test.bin ]; then
#	make -C /Local/ma/yast2/current/source/core/wfm/src || exit 1
#fi
$MAKE $PRG || exit 1

export Y2SLOG_FILE=-
export Y2SLOG_DEBUG=
export Y2DEBUG=1
#exec gdb ./$PRG
#./$PRG "$@" 2> log
./$PRG "$@" 2> $LPIPE

