#!/bin/bash
# query rpm and output a format that can be parsed by autosolvertest
rpm -q "$@" --qf \
"Name: %{NAME}
Edition: %{VERSION}-%{RELEASE}
Conflicts: [%{CONFLICTNAME}%|CONFLICTFLAGS?{ %{CONFLICTFLAGS:depflags} %{CONFLICTVERSION}}:{}|, ]
Obsoletes: [%{OBSOLETENAME}%|OBSOLETEFLAGS?{ %{OBSOLETEFLAGS:depflags} %{OBSOLETEVERSION}}:{}|, ]
Provides:  [%{PROVIDENAME}%|PROVIDEFLAGS?{ %{PROVIDEFLAGS:depflags} %{PROVIDEVERSION}}:{}|, ]
Requires:  [%{REQUIRENAME}%|REQUIREFLAGS?{ %{REQUIREFLAGS:depflags} %{REQUIREVERSION}}:{}|, ]

"
