#! /bin/bash
#
PRG=ma_test.exe

make -C ../src && make || exit 1

if [ ! -x ~ma/bin/sy2l.tcl ]; then
	exec ./$PRG
fi

LPIPE=Y2LOGFILE
test -p "$LPIPE" || {
        test -e "$LPIPE" && { echo "No pipe '$LPIPE' exists"; exit 1; }
        mkfifo $LPIPE
}
if ! fuser $LPIPE >/dev/null; then
        ~ma/bin/sy2l.tcl $LPIPE &
fi

export Y2SLOG_FILE=-
export Y2SLOG_DEBUG=
# export Y2DEBUG=1
./$PRG 2> $LPIPE
